### ISSUE TITLE
Materialization in Repositories

### ISSUE THREAD

**Issue by PetrSvirak** [sutrkiller/MyWallet#15]
Materialization on Entities level of the API does not make sense.

Imagine 30.000 entries in the DB and you want to display 15 on a page/listing. The GetAllEntries method will download all of them to the memory and filtering, likely performed by a service, will be done in memory while it could and should be done by the database engine. Do not return an in-memory collection, rather "publish" an IQueriable<> type.

Later, when services are more specific on what they actually request from the repository, you will see there is usually a where condition and paging involved. If you want to be fancy, you can introduce mechanisms to pass condition(s) and paging into the repository and return an in-memory collection later.

**Comment by sutrkiller** [comment]
Should be solved in commit d765f335a82e28a789bb0d8144ae7ad03ffb0d79.
