### ISSUE TITLE
Incorrect references

### ISSUE THREAD

**Issue by PetrSvirak** [sutrkiller/MyWallet#16]
The project MyWallet.Entities do not have NuGet references set correctly. Follow the suggestion in the marked comment and fix this issue.

Right now, it is only coincidence that most of you can build your solution. Whoever put the reference into the project file (possibly manually) did it wrong; generally leave this on NuGet and mostly do check what was done in project file prior commit.

**Comment by sutrkiller** [comment]
Building problems now resolved with recreation of solution structure in commit 84cfff6e80cbfcbadfd9ead0fa204e17f03b38bf.
