### ISSUE TITLE
Empty classes and projects in solution

### ISSUE THREAD

**Issue by PetrSvirak** [sutrkiller/MyWallet#17]
Empty classes (`class1.cs` without any implementation) should never be committed to the master branch. Also, there is no reason to have an empty project in the master branch. I can think of only one reason and that is to set references within your solution just right. It is pretty weak and it can only apply to non-test projects (MyWallet.Services in your case) - all other projects should not be present in Master branch unless having at least one class with a meaningful purpose.

**Comment by sutrkiller** [comment]
This issue should be resolved with recreation of solution structure in commit 84cfff6e80cbfcbadfd9ead0fa204e17f03b38bf
