### ISSUE TITLE
Abbreviations in class names

### ISSUE THREAD

**Issue by PetrSvirak** [sutrkiller/MyWallet#27]
First of all, you lack class-naming rule amidst your coding rules (add it, please). If it were there, it would probably state the name of a class should be in PascalCase. All the _*DTO_ objects would break this rule then.

Second, there is usually no need for the abbreviations and they are usually misleading (imagine the sentense: "DAL is done right when you do not have to justify BL to your PL" ~ "[Dope Ass Lifestyle](http://www.urbandictionary.com/define.php?term=Dal) is done right when you do not have to justify [boys love](http://www.urbandictionary.com/define.php?term=BL) to your [psycho lesbian](http://www.urbandictionary.com/define.php?term=pl&defid=5098974) (friend)" ;-))

Third, while database layer is usually not exposed, service layer is (usually) part of public API your clients actually use. You do not want to let your API scream 3-letter words on other people, especially if your rely on their payments.

In your case, the fix should be easy enough. Just remove _DAL_ suffix from all your service objects (or any other abbreviations I would find later) and let the namespaces solve the same naming issue for you.

**Comment by sutrkiller** [comment]
Renamed in commit 54e0ae81397c585d2220a4290ac2e1d155e6dce1
